---
# This is a sample database file for the DataMapper ORM
development: &defaults
  # These are the settings for repository :default
  adapter:  mysql
  database: mostfit_test
  username: root
  password: hatstars
  host: localhost
#   adapter: sqlite3
#   database: db/development.db
 
test:
  <<:       *defaults
  database: db/test.db
 
production:
  adapter:  mysql
  database: mostfit_db
  username: mostfit_user 
  password: p4ssw0rd
  host:     localhost

 
rake:
  <<: *defaults
